// ============================================================
// STEP 1: INITIALIZATION & STATE
// ============================================================
const h1 = document.querySelector('h1');
const h2 = document.querySelector('h2');
const body = document.querySelector('body');

// Config Data
let buttons = ['red', 'green', 'blue', 'yellow'];

// State Tracking
let gameSeq = []; // Stores the pattern generated by the computer
let userSeq = []; // Stores the pattern clicked by the user
let level = 0; // Current Level
let gameStarted = false; // Prevents game from starting multiple times

// ============================================================
// STEP 2: START GAME LOGIC
// ============================================================
function main() {
    // Only run if the game hasn't started yet
    if (gameStarted === false) {
        body.classList.remove('redflash'); // Clean up any previous Game Over red screen
        gameStarted = true;

        console.log('Game Started? Yes!');
        console.log('');

        levelUp();
    }
}

// ============================================================
// STEP 3: LEVEL UP LOGIC
// ============================================================
function levelUp() {
    userSeq = []; // CRITICAL: Reset user's sequence for the new level
    level++;

    h1.innerHTML = '<b>Simon Game</b>';
    h2.innerText = `Level ${level}`;

    // 1. Pick a random index (0-3)
    let randomIndex = Math.floor(Math.random() * 4);

    // 2. Map index to a color string (e.g., 2 -> 'blue')
    let randomColor = buttons[randomIndex];

    // 3. Add new color to the Master Sequence
    gameSeq.push(randomColor);
    console.log("Game's sequence", gameSeq);

    // 4. Play the sequence back to the user
    // We replay the ENTIRE sequence (Old + New) so the user can memorize the pattern.
    playSequence();
}

// ============================================================
// STEP 4: SEQUENCE PLAYER (The Interval Timer)
// ============================================================
function playSequence() {
    let i = 0;

    // UX: Disable clicks while the computer is showing the sequence
    // This prevents the user from clicking too early and messing up the order.
    document.body.style.pointerEvents = 'none';

    const intervalId = setInterval(() => {
        // STOP CONDITION: If we have flashed all buttons in the array
        if (i >= gameSeq.length) {
            clearInterval(intervalId);
            // Re-enable clicks so user can play
            document.body.style.pointerEvents = 'auto';
            return;
        }

        // Get color from the sequence
        let buttonColor = gameSeq[i];

        // Select the actual HTML element
        let button = document.querySelector(`.${buttonColor}`);

        // Flash it visually
        gameFlash(button);

        // Move to next color in sequence
        i++;
    }, 1000); // 1 Second delay between flashes
}

// ============================================================
// STEP 5: VISUAL EFFECTS
// ============================================================
function gameFlash(btn) {
    btn.classList.add('flash'); // Add white glow
    setTimeout(() => {
        btn.classList.remove('flash'); // Remove it after 0.5s
    }, 500);
}

// ============================================================
// STEP 6: USER INTERACTION HANDLER
// ============================================================
let allButtons = document.querySelectorAll('.btn');

for (let i of allButtons) {
    // Added 'let' for safety
    i.addEventListener('click', function () {
        let clickedButton = this;
        gameFlash(clickedButton); // Visual feedback for user click

        // 1. Get the color ID of the clicked button
        let userClickedColor = clickedButton.id;

        // 2. Add to User's Sequence
        userSeq.push(userClickedColor);

        // 3. CHECK ANSWER
        // We pass "userSeq.length - 1".
        // MEANING: This represents the INDEX of the button just clicked.
        // Example: If I just clicked the 3rd button, length is 3. Index is 2.
        // We want to check ONLY the most recent click immediately.
        seqCheck(userSeq.length - 1);
    });
}

// ============================================================
// STEP 7: GAME LOGIC CHECKER
// ============================================================
function seqCheck(idx) {
    // CHECK 1: Did the user click the correct color at this specific step?
    if (userSeq[idx] === gameSeq[idx]) {
        // CHECK 2: Was that the LAST color in the sequence?
        if (userSeq.length === gameSeq.length) {
            console.log(`Level ${level} cleared!`);
            // Wait 1 second, then start next level
            setTimeout(levelUp, 1000);
        }
    } else {
        // FAILURE: User clicked wrong color
        h1.innerText = 'Game Over!';
        h2.innerHTML = `<b>Your score was ${level - 1}</b><br>Press any key to start again.`;

        // Visual Red Flash on background
        body.classList.add('redflash');
        setTimeout(() => {
            reset();
        }, 500);
    }
}

// ============================================================
// STEP 8: RESET STATE
// ============================================================
function reset() {
    // Disable clicks until user restarts
    document.body.style.pointerEvents = 'none';
    gameStarted = false;
    gameSeq = [];
    level = 0;
}

// ============================================================
// EVENT LISTENERS (Start Game)
// ============================================================
document.addEventListener('keydown', main);
document.addEventListener('click', main);
